train_data_path: "/20A021/dataset_from_dyl/train-50up/lmdb_path_ub/train"
valid_data_path: "/20A021/dataset_from_dyl/train-50up/lmdb_path_ub/valid"
save_path: "/20A021/projects/audiossl/savedir/pretrain/0627"
nproc: 2
devices: 0,1
max_epochs: 100
warmup_epochs: 10
# warmup_steps: 1950 # 在train.py计算出来
# max_steps: 58500 # 在train.py计算出来
subset: 432325 # audio的总个数，这里是42447个片段，按照20s stride, 30s window_size裁剪之后的个数
ema: 0.997
learning_rate: 5.0e-5 # 1.0e-4
batch_size_per_gpu: 128
symmetric: True
aug_tea: False #
aug_stu: True
arch: small
mask_ratio: 0.65
mask_type: "block"
sr: 22050  #16000
# 用于重新计算输入新的patch_w, 在audio_transformer.py, return FrameAST()
n_fft: 2048 #
win_length: 2048 #640 一般默认是hop_length的四倍, <=n_fft
hop_length: 512  #160
anchor_len: 30
n_mels: 64 # 这个参数在FrameASTclass当中，对应的是spec_h
spec_w: 1292 # 原来的参数是1001，计算方式是 sr*anchor_len//hop_length + 1，这里的//是floor division. 对应于transform.py里num_patches的计算方式
patch_h: 64
patch_w: 4
mask_len: 5
pos_type: "cut"
num_workers: 10
